# Generated by Django 5.2.15 on 2026-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConformalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(upload_to='sources/')),
                ('transformed_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transform_type', models.CharField(choices=[('DROSTE', 'Standard Droste'), ('ESCHER_DROSTE', 'Escher Conformal Spiral'), ('MOBIUS', 'Möbius Transformation')], default='ESCHER_DROSTE', max_length=20)),
                ('r1', models.FloatField(default=0.1, help_text='Inner frame radius boundary')),
                ('r2', models.FloatField(default=1.0, help_text='Outer frame radius boundary')),
                ('center_x', models.IntegerField(blank=True, help_text='Custom X focus center', null=True)),
                ('center_y', models.IntegerField(blank=True, help_text='Custom Y focus center', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
