# Generated by Django 5.2.15 on 2026-06-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformaltask',
            name='img_size_scale',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='conformaltask',
            name='math_scale',
            field=models.FloatField(default=3.141592653589793),
        ),
        migrations.AddField(
            model_name='conformaltask',
            name='source_zoom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conformaltask',
            name='x_bound_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conformaltask',
            name='x_bound_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conformaltask',
            name='y_bound_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conformaltask',
            name='y_bound_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
