# Generated by Django 5.2.15 on 2026-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_mapper', '0003_alter_conformaltask_img_size_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformaltask',
            name='transform_type',
            field=models.CharField(choices=[('THREE BLUE DROSTE', 'Twisted 3b Droste'), ('STRAIGHT_DROSTE', 'Straight Droste (No Twist)'), ('MOBIUS', 'Möbius Transformation'), ('EXP', 'Complex Exponential (e^z)'), ('LOG', 'Complex Logarithm (ln(z))'), ('DISTORT', 'Sinusoidal Distortion')], default='THREE BLUE DROSTE', max_length=20),
        ),
    ]
