# Generated by Django 5.2.15 on 2026-06-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_mapper', '0004_alter_conformaltask_transform_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conformaltask',
            name='r1',
        ),
        migrations.RemoveField(
            model_name='conformaltask',
            name='r2',
        ),
        migrations.AlterField(
            model_name='conformaltask',
            name='transform_type',
            field=models.CharField(default='THREE BLUE DROSTE', help_text='Comma-separated chain sequence of transformation steps (e.g., MOBIUS,EXP)', max_length=255),
        ),
    ]
