# Generated by Django 5.2.15 on 2026-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_mapper', '0005_remove_conformaltask_r1_remove_conformaltask_r2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformaltask',
            name='custom_expression',
            field=models.TextField(blank=True, help_text="Custom Python/NumPy math expression using the variable 'z'", null=True),
        ),
    ]
