import math

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from .models import ConformalTask
from .tasks import process_conformal_mapping

@csrf_exempt
def transform_image_view(request):
    if request.method != 'POST':
        return JsonResponse({'error': 'Only POST requests allowed'}, status=405)

    if not request.FILES.get('image'):
        return JsonResponse({'error': 'No image file uploaded'}, status=400)

    try:
        # Grabs the comma-separated string generated by your frontend JS
        transform_type = request.POST.get('type', 'THREE BLUE DROSTE')

        cx = request.POST.get('center_x')
        cy = request.POST.get('center_y')

        math_scale = float(request.POST.get('math_scale', math.pi))
        img_size_scale = int(request.POST.get('img_size_scale', 1))

        zoom = request.POST.get('source_zoom')
        xb_min = request.POST.get('x_bound_min')
        xb_max = request.POST.get('x_bound_max')
        yb_min = request.POST.get('y_bound_min')
        yb_max = request.POST.get('y_bound_max')

        # Check explicit checkbox payload fallback state
        if request.POST.get('auto_zoom_sqrt2') in ['on', 'true']:
            zoom = math.sqrt(2)
        else:
            raw_zoom = request.POST.get('source_zoom')
            zoom = float(raw_zoom) if raw_zoom else None

        task = ConformalTask.objects.create(
            source_image=request.FILES['image'],
            transform_type=transform_type,
            center_x=int(cx) if cx else None,
            center_y=int(cy) if cy else None,
            math_scale=math_scale,
            img_size_scale=img_size_scale,
            source_zoom=float(zoom) if zoom else None,
            x_bound_min=float(xb_min) if xb_min else None,
            x_bound_max=float(xb_max) if xb_max else None,
            y_bound_min=float(yb_min) if yb_min else None,
            y_bound_max=float(yb_max) if yb_max else None,
            status='PENDING'
        )

        process_conformal_mapping.delay(task.id)    # delegate to celery

        return JsonResponse({
            'task_id': task.id,
            'status': task.status,
            'message': 'Task successfully queued.'
        }, status=202)

    except ValueError as val_err:
        return JsonResponse({
            'error': f'Invalid parameter formatting numerical conversions: {str(val_err)}'
        }, status=400)


def task_status_view(request, task_id):     # called repeatedly while waiting for results
    try:
        task = ConformalTask.objects.get(id=task_id)
        response_data = {
            'task_id': task.id,
            'status': task.status,
            'created_at': task.created_at,
        }

        if task.status == 'COMPLETED':
            response_data['result_url'] = task.transformed_image.url
        elif task.status == 'FAILED':
            response_data['error_message'] = task.error_message

        return JsonResponse(response_data)
    except ConformalTask.DoesNotExist:
        return JsonResponse({'error': 'Task not found'}, status=404)


def dashboard_view(request):
    """
    Renders the interactive prototype UI dashboard.
    """
    return render(request, 'image_mapper/dashboard.html')
